blog/urls.py
from django.urls import path
from . import views

# start with blog
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('blog_search', views.blog_search, name='blog_search'),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name="blogs_with_type"),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('user_info', views.user_info, name='user_info'),
    path('change_nickname', views.change_nickname, name='change_nickname'),
    path('change_email', views.change_email, name='change_email'),
    path('bind_phone', views.bind_phone, name='bind_phone'),
    path('change_phone', views.change_phone, name='change_phone'),
    path('send_msg_verification_code', views.send_msg_verification_code, name='send_msg_verification_code'),
    path('send_email_verification_code', views.send_email_verification_code, name='send_email_verification_code'),
    path('change_password', views.change_password, name='change_password'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('user_avatar', views.user_avatar, name='user_avatar'),
    path('user_avatar_upload', views.user_avatar_upload, name='user_avatar_upload'),
]

user/models.py
import os
import shutil
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

# 头像路径

AVATAR_ROOT = 'media/static/avatar'
AVATAR_DEFAULT = os.path.join(AVATAR_ROOT, 'default.png')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='昵称')
    nickname = models.CharField(max_length=20)

    class Meta:
        verbose_name = '昵称'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '<Profile:%s for %s>' % (self.nickname, self.user.username)


class Phone_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='电话')
    phone = models.CharField(max_length=11)

    class Meta:
        verbose_name = '电话'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '<Phone:%s >' % (self.phone)


class Avatar(models.Model):
    """user avatar"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='头像')
    avatar = models.ImageField(upload_to=AVATAR_ROOT)

    class Meta:
        verbose_name = '头像'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '<Avatar:%s >' % (self.avatar)


# 获取昵称
def get_nickname(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return ''


# 获取用户名或昵称
def get_nickname_or_username(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return self.username


# 有昵称
def has_nickname(self):
    return Profile.objects.filter(user=self).exists()


# 获取电话
def get_phone(self):
    if Phone_Profile.objects.filter(user=self).exists():
        phone_profile = Phone_Profile.objects.get(user=self)
        return phone_profile.phone
    else:
        return ''


# 动态绑定头像相关的方法
def get_avatar_url(self):
    try:
        avatar = Avatar.objects.get(user=self)
        return avatar.avatar
    except Exception:
        return AVATAR_DEFAULT


def set_avatar_url(self, src_path):
    try:
        avatar = Avatar.objects.filter(user=self.id)[0]
        old_path = os.path.join(settings.BASE_DIR, avatar.avatar.name)  # 旧的头像路径

    except Exception:
        avatar = Avatar(user=self)
        old_path = ''

    # # 删除旧文件
    # if os.path.isfile(old_path):
    #     os.remove(old_path)
    # else:
    #     print('not have')
    # return avatar

    # 根据user id设置新的头像名称
    filename = os.path.split(src_path)[-1]
    img_format = os.path.splitext(filename)[-1]

    new_filename = 'avatar_%s%s' % (self.id, img_format)
    new_path = os.path.join(settings.BASE_DIR, AVATAR_ROOT, new_filename)

    # 保存头像
    shutil.copy(src_path, new_path)
    avatar.avatar = os.path.join(AVATAR_ROOT, new_filename)
    avatar.save()
    return avatar


# 动态绑定方法
User.set_avatar_url = set_avatar_url

# 动态绑定方法
# User.get_avatar_url = MethodType(get_avatar_url, User)
User.get_avatar_url = get_avatar_url

User.get_nickname = get_nickname
User.has_nickname = has_nickname
User.get_nickname_or_username = get_nickname_or_username

User.get_phone = get_phone

user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from ckeditor.widgets import CKEditorWidget


class LoginForm(forms.Form):
    username_or_email = forms.CharField(label='用户名或邮箱',
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control', 'placeholder': '请输入用户名'
                                                   })
                                        )
    password = forms.CharField(label='密码',
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'
                                                                 })
                               )

    def clean(self):
        username_or_email = self.cleaned_data['username_or_email']
        password = self.cleaned_data['password']

        user = auth.authenticate(username=username_or_email, password=password)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data['user'] = user
                    return self.cleaned_data
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


class RegForm(forms.Form):
    username = forms.CharField(label='用户名',
                               max_length=30,
                               min_length=3,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control', 'placeholder': '请输入3-30位用户名'
                                   })
                               )
    phone = forms.CharField(label='手机号',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control', 'placeholder': '请输入11位手机号'
                                })
                            )
    verification_code = forms.CharField(label='验证码',
                                        max_length=6,
                                        required=False,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control',
                                                   'placeholder': '点击"发送验证码"发送到手机'
                                                   })
                                        )
    password = forms.CharField(label='密码',
                               min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'}))
    password_again = forms.CharField(label='再输入一次密码',
                                     min_length=6,
                                     widget=forms.PasswordInput(
                                         attrs={'class': 'form-control', 'placeholder': '再输入一次密码'}))

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断验证码
        code = self.request.session.get('register_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username


    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('两次输入的密码不一致')
        return password_again

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code


class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(label='新的昵称',
                                   max_length=20,
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': 'form-control', 'placeholder': '请输入新的昵称'
                                       })
                                   )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户尚未登录')
        return self.cleaned_data

    def clean_nickname_new(self):
        nickname_new = self.cleaned_data.get('nickname_new', '').strip()
        if nickname_new == '':
            raise forms.ValidationError('新的昵称不能为空')
        return nickname_new


class ChangeEmailForm(forms.Form):
    email = forms.EmailField(label='修改邮箱',
                             widget=forms.EmailInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': '请输入新的邮箱'
                                        })
                             )
    verification_code = forms.CharField(label='验证码',
                                        max_length=4,
                                        required=False,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control',
                                                   'placeholder': '点击"发送验证码"发送到邮箱'
                                                   })
                                        )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ChangeEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户尚未登录')
        # 判断验证码
        code = self.request.session.get('bind_email_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已被绑定')
        return email

    def clean_emial_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code


class ChangePhoneForm(forms.Form):
    phone = forms.CharField(label='新的手机号',
                            max_length=11,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control',
                                       'placeholder': '请输入新的手机号'
                                       })
                            )
    verification_code = forms.CharField(label='验证码',
                                        max_length=4,
                                        required=False,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control',
                                                   'placeholder': '点击"发送验证码"发送到手机'
                                                   })
                                        )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ChangePhoneForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户尚未登录')
        # 判断验证码
        code = self.request.session.get('change_phone_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if User.objects.filter(phone_profile__phone=phone).exists():
            raise forms.ValidationError('手机号已被绑定')
        return phone

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code


class BindPhoneForm(forms.Form):
    phone = forms.CharField(label='手机号',
                            max_length=20,
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control', 'placeholder': '请输入手机号'
                                })
                            )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(BindPhoneForm, self).__init__(*args, **kwargs)

    def clean(self):

user/templates/user/avatar.html
{% extends 'base.html' %}
{% load static %}
{% block title %}修改头像{% endblock %}
{% block header_extends %}
    <link rel="stylesheet" type="text/css" href="{% static 'cropper.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/avatar.css' %}">
    <script src="/static/cropper.js"></script>
{% endblock %}
{% block content %}
    <div class="col-sm-10">
        <!--编辑区域-->
        <p id="tip-text" class="alert alert-success">点击本地图片上传一张照片呗~</p>
        <div class="avatar-wrapper" id='avatar-wrapper'>
            <img src="">
        </div>
        <br>
        <!--编辑相关数据-->
        <form id="avatar_form">
            <div>
                <input type="hidden" id="avatar_x" name="avatar_x">
                <input type="hidden" id="avatar_y" name="avatar_y">
                <input type="hidden" id="avatar_width" name="avatar_width">
                <input type="hidden" id="avatar_height" name="avatar_height">
                <input style="display:none" type="file" class="avatar-input" id="avatar-input" name="avatar_file"
                       accept=".jpg,.jpeg,.png">
            </div>
        </form>
        <div>
            <label class="btn btn-primary" for="avatar-input">本地图片</label>
            &emsp;&emsp;&emsp;
            <button class="btn btn-primary">
                <span class="glyphicon glyphicon-zoom-in" id="zoom-in" aria-hidden="true"></span></button>
            <button class="btn btn-primary">
                <span class="glyphicon glyphicon-zoom-out" id="zoom-out" aria-hidden="true"></span>
            </button>
            <button class="btn btn-primary">
                <span class="glyphicon glyphicon-refresh" id="reset" aria-hidden="true"></span>
            </button>
        </div>
    </div>

    <div class="col-sm-2">
        <!--头像预览-->
        <div class="avatar-preview"><img style="width: 96px; height: 96px;" src="/{{ user.get_avatar_url }}"></div>
        <a id="avatar-upload" name="avatar-upload" href="#" class="btn btn-primary disabled">上传头像</a>
    </div>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $(function () {
            //初始化裁剪器
            var image = $('#avatar-wrapper img');
            image.cropper({
                checkImageOrigin: true, //检查图片来源
                dragMode: 'move',   //图片可移动
                restore: false,      //窗体调整大小之后不自动恢复裁剪区域
                zoomOnWheel: false, //不允许通过鼠标滚轮缩放
                zoomOnTouch: false, //不允许通过触摸缩放
                aspectRatio: 1 / 1, //裁剪比例
                autoCropArea: 0.5,  //裁剪背景透明度
                autoCropArea: 1,    //自动裁剪的比例

                //文本的jQuery选择表达式，一个div
                preview: $(".avatar-preview").selector,
                crop: function (e) {
                    e = e.detail
                    //返回图片编辑相关数据
                    $('#avatar_x').val(e.x);
                    $('#avatar_y').val(e.y);
                    $('#avatar_width').val(e.width);
                    $('#avatar_height').val(e.height);
                },
            });
            $("#avatar-input").change(function () {
                var URL = window.URL || window.webkitURL;
                if (URL) {
                    var files = this.files;
                    if (files && files.length) {
                        var file = files[0];
                        if (/^image\/\w+$/.test(file.type)) {
                            var blobURL = URL.createObjectURL(file);
                            image.cropper('reset').cropper('replace', blobURL);
                            $('#avatar-upload').removeClass('disabled');
                            normal_tip('本地图片：可调整到最佳状态再上传');
                        } else {
                            error_tip('请选择一张图片');
                        }
                    }
                }
            });
            $("#avatar-upload").click(function () {
                if ($('#avatar-wrapper img').attr('src') == '') {
                    alert('亲~ 你是不是忘记选择图片了');
                    return false;
                }
                //注意：FormData中的[0]是必备的
                var formData = new FormData($("#avatar_form")[0]);
                $.ajax({
                    url: "{%url 'user_avatar_upload'%}",
                    type: 'POST',
                    data: formData,
                    async: false,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        normal_tip("头像上传成功");
                        window.location.href = '/user/user_info';
                    },
                    error: function (err) {
                        error_tip("提交失败，请重试！");
                    }
                });
                return false;
            });
            var zoom = 1;
            $("#zoom-in").click(function () {
                if (zoom < 1.5) {
                    zoom += 0.1;
                    image.cropper("zoom", 0.1);
                }
            });
            $("#zoom-out").click(function () {
                if (zoom > 0.5) {
                    zoom -= 0.1;
                    image.cropper("zoom", -0.1);
                }
            });
            //复位按钮
            $('#reset').click(function () {
                image.cropper("reset");
                zoom = 1;
            });
        });

        function error_tip(text) {
            $('#tip-text').removeClass();
            $('#tip-text').addClass('alert alert-danger');
            $('#tip-text').text(text);
        }

        function normal_tip(text) {
            $('#tip-text').removeClass();
            $('#tip-text').addClass('alert alert-info');
            $('#tip-text').text(text);
        }

    </script>
{% endblock %}
</body>
</html>

user/templates/user/bind_email.html
{% extends 'form.html' %}
{% block others_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $('#send_code').click(function () {
            {#发送验证码后禁止修改邮箱#}
            $("#id_email").addClass('disabled');
            $("#id_email").attr('disabled', true);
            var email = $("#id_email").val();
            if (email == "") {
                $("#tip").text('邮箱不能为空');
                return false;
            }
            $.ajax({
                url: "{% url 'send_verification_code' %}",
                type: "GET",
                data: {
                    'email': email,
                    'send_for':'bind_email_code'
                },
                cache: false,
                success: function (data) {
                    if (data['status'] == 'ERROR') {
                        alert(data['status']);
                    }

                }
            });
            {#    使发送按钮变灰#}
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 'S');
            var interval = setInterval(() => {
                if (time < 0) {
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time--;
                $(this).text(time + 'S');
            }, 1000);
        });
    </script>
{% endblock %}

user/templates/user/change_email.html
{% extends 'form.html' %}
{% block others_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $('#send_code').click(function () {
            {#发送验证码后禁止修改邮箱#}
            var email = $("#id_email").val();
            if (email == "") {
                $("#tip").text('邮箱不能为空');
                return false;
            }
            $("#id_email").addClass('readonly');
            $("#id_email").attr('readonly', true);
            $.ajax({
                url: "{% url 'send_email_verification_code' %}",
                type: "GET",
                data: {
                    'email': email,
                    'send_for': 'bind_email_code'
                },
                cache: false,
                success: function (data) {
                    if (data['status'] == 'ERROR') {
                        alert(data['status']);
                    }

                }
            });
            {#    使发送按钮变灰#}
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 60;
            $(this).text(time + 'S');
            var interval = setInterval(() => {
                if (time < 1) {
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time--;
                $(this).text(time + 'S');
            }, 1000);
        });
    </script>
{% endblock %}

user/templates/user/change_phone.html
{% extends 'form.html' %}
{% block others_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $('#send_code').click(function () {
            {#发送验证码后禁止修改手机号#}
            $("#id_phone").addClass('readonly');
            $("#id_phone").attr('readonly', true);
            var phone = $("#id_phone").val();
            if (phone == "") {
                $("#tip").text('手机号不能为空');
                return false;
            }
            $.ajax({
                url: "{% url 'send_msg_verification_code' %}",
                type: "GET",
                data: {
                    'phone': phone,
                    'send_for':'change_phone_code'
                },
                cache: false,
                success: function (data) {
                    if (data['status'] == 'ERROR') {
                        alert(data['status']);
                    }

                }
            });
            {#    使发送按钮变灰#}
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 60;
            $(this).text(time + 'S');
            var interval = setInterval(() => {
                if (time < 1) {
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time--;
                $(this).text(time + 'S');
            }, 1000);
        });
    </script>
{% endblock %}

user/templates/user/forgot_password.html
{% extends 'form.html' %}
{% block others_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $('#send_code').click(function () {
            {#发送验证码后禁止修改邮箱#}
            $("#id_email").addClass('disabled');
            $("#id_email").attr('disabled', true);
            var email = $("#id_email").val();
            if (email == "") {
                $("#tip").text('邮箱不能为空');
                return false;
            }
            $.ajax({
                url: "{% url 'send_msg_verification_code' %}",
                type: "GET",
                data: {
                    'email': email,
                    'send_for': 'forgot_password_code'
                },
                cache: false,
                success: function (data) {
                    if (data['status'] == 'ERROR') {
                        alert(data['status']);
                    }

                }
            });
            {#    使发送按钮变灰#}
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 60;
            $(this).text(time + 'S');
            var interval = setInterval(() => {
                if (time < 1) {
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time--;
                $(this).text(time + 'S');
            }, 1000);
        });
    </script>
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in reg_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class="text-danger">{{ reg_form.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <button id="send_code" class="btn btn-primary pull-left">发送验证码</button>
                                <input type="submit" value="注册" class="btn btn-primary pull-right">
                            </form>

                        </div>
                    </div>
                {% else %}
                    <span>已登录，即将跳转到首页</span>
                    <script type="text/javascript">
                        window.location.href = "/";
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $('#send_code').click(function () {
            var email = $("#id_email").val();
            var phone = $("#id_phone").val();
            if (email == "") {
                $("#tip").text('邮箱不能为空');
                return false;
            }
            if (phone == "") {
                $("#tip").text('手机号不能为空');
                return false;
            }
            $("#id_email").addClass('readonly');
            $("#id_email").attr('readonly', true);
            $("#id_phone").addClass('readonly');
            $("#id_phone").attr('readonly', true);
            $.ajax({
                url: "{% url 'send_msg_verification_code' %}",
                type: "GET",
                data: {
                    'phone': phone,
                    'send_for': 'register_code'
                },
                cache: false,
                success: function (data) {
                    if (data['status'] == 'ERROR') {
                        alert(data['status']);
                    }

                }
            });
            {#使发送按钮变灰#}
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 60;
            $(this).text(time + 'S');
            var interval = setInterval(() => {
                if (time < 1) {
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time--;
                $(this).text(time + 'S');
            }, 1000);
        });
    </script>
{% endblock %}